version: '3.9'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_USER: bank-user
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret

  bank_service:
    build:
      context: .
    container_name: bank_service
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin_data:
