log: "local"
env: "dev"

postgres:
  host: "postgres"
  port: 5432
  user: "bank-user"
  password: "secretpass"
  db_name: "bank"
  maxconn: 100

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "user"
  password: "secret"

rest:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 10s

